# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CodeGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Edge(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # Edge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Edge
    def SourceId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Edge
    def TargetId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Edge
    def Type(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateEdge(builder, sourceId, targetId, type):
    builder.Prep(4, 12)
    builder.Pad(3)
    builder.PrependInt8(type)
    builder.PrependInt32(targetId)
    builder.PrependInt32(sourceId)
    return builder.Offset()
