# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CodeGraph

class EdgeType(object):
    Unknown = 0
    Includes = 1
    Inherits = 2
    Calls = 3
    Reads = 4
    Writes = 5
