# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CodeGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GraphPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GraphPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGraphPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GraphPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GraphPayload
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GraphPayload
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from CodeGraph.Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GraphPayload
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphPayload
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # GraphPayload
    def Edges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from CodeGraph.Edge import Edge
            obj = Edge()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GraphPayload
    def EdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GraphPayload
    def EdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def GraphPayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    GraphPayloadStart(builder)

def GraphPayloadAddVersion(builder, version):
    builder.PrependInt32Slot(0, version, 0)

def AddVersion(builder, version):
    GraphPayloadAddVersion(builder, version)

def GraphPayloadAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    GraphPayloadAddNodes(builder, nodes)

def GraphPayloadStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems: int) -> int:
    return GraphPayloadStartNodesVector(builder, numElems)

def GraphPayloadAddEdges(builder, edges):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder, edges):
    GraphPayloadAddEdges(builder, edges)

def GraphPayloadStartEdgesVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartEdgesVector(builder, numElems: int) -> int:
    return GraphPayloadStartEdgesVector(builder, numElems)

def GraphPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return GraphPayloadEnd(builder)
