# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CodeGraph

class NodeType(object):
    Unknown = 0
    File = 1
    Class = 2
    Struct = 3
    Function = 4
    Method = 5
    Variable = 6
