// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAPH_CODEGRAPH_H_
#define FLATBUFFERS_GENERATED_GRAPH_CODEGRAPH_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace CodeGraph {

struct Node;
struct NodeBuilder;

struct Edge;

struct GraphPayload;
struct GraphPayloadBuilder;

enum NodeType : int8_t {
  NodeType_Unknown = 0,
  NodeType_File = 1,
  NodeType_Class = 2,
  NodeType_Struct = 3,
  NodeType_Function = 4,
  NodeType_Method = 5,
  NodeType_Variable = 6,
  NodeType_MIN = NodeType_Unknown,
  NodeType_MAX = NodeType_Variable
};

inline const NodeType (&EnumValuesNodeType())[7] {
  static const NodeType values[] = {
    NodeType_Unknown,
    NodeType_File,
    NodeType_Class,
    NodeType_Struct,
    NodeType_Function,
    NodeType_Method,
    NodeType_Variable
  };
  return values;
}

inline const char * const *EnumNamesNodeType() {
  static const char * const names[8] = {
    "Unknown",
    "File",
    "Class",
    "Struct",
    "Function",
    "Method",
    "Variable",
    nullptr
  };
  return names;
}

inline const char *EnumNameNodeType(NodeType e) {
  if (::flatbuffers::IsOutRange(e, NodeType_Unknown, NodeType_Variable)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNodeType()[index];
}

enum EdgeType : int8_t {
  EdgeType_Unknown = 0,
  EdgeType_Includes = 1,
  EdgeType_Inherits = 2,
  EdgeType_Calls = 3,
  EdgeType_Reads = 4,
  EdgeType_Writes = 5,
  EdgeType_MIN = EdgeType_Unknown,
  EdgeType_MAX = EdgeType_Writes
};

inline const EdgeType (&EnumValuesEdgeType())[6] {
  static const EdgeType values[] = {
    EdgeType_Unknown,
    EdgeType_Includes,
    EdgeType_Inherits,
    EdgeType_Calls,
    EdgeType_Reads,
    EdgeType_Writes
  };
  return values;
}

inline const char * const *EnumNamesEdgeType() {
  static const char * const names[7] = {
    "Unknown",
    "Includes",
    "Inherits",
    "Calls",
    "Reads",
    "Writes",
    nullptr
  };
  return names;
}

inline const char *EnumNameEdgeType(EdgeType e) {
  if (::flatbuffers::IsOutRange(e, EdgeType_Unknown, EdgeType_Writes)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEdgeType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Edge FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t source_id_;
  int32_t target_id_;
  int8_t type_;
  int8_t padding0__;  int16_t padding1__;

 public:
  Edge()
      : source_id_(0),
        target_id_(0),
        type_(0),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  Edge(int32_t _source_id, int32_t _target_id, CodeGraph::EdgeType _type)
      : source_id_(::flatbuffers::EndianScalar(_source_id)),
        target_id_(::flatbuffers::EndianScalar(_target_id)),
        type_(::flatbuffers::EndianScalar(static_cast<int8_t>(_type))),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  int32_t source_id() const {
    return ::flatbuffers::EndianScalar(source_id_);
  }
  int32_t target_id() const {
    return ::flatbuffers::EndianScalar(target_id_);
  }
  CodeGraph::EdgeType type() const {
    return static_cast<CodeGraph::EdgeType>(::flatbuffers::EndianScalar(type_));
  }
};
FLATBUFFERS_STRUCT_END(Edge, 12);

struct Node FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_NAME = 8,
    VT_FILE_PATH = 10,
    VT_START_LINE = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  CodeGraph::NodeType type() const {
    return static_cast<CodeGraph::NodeType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *file_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_PATH);
  }
  int32_t start_line() const {
    return GetField<int32_t>(VT_START_LINE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_FILE_PATH) &&
           verifier.VerifyString(file_path()) &&
           VerifyField<int32_t>(verifier, VT_START_LINE, 4) &&
           verifier.EndTable();
  }
};

struct NodeBuilder {
  typedef Node Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(Node::VT_ID, id, 0);
  }
  void add_type(CodeGraph::NodeType type) {
    fbb_.AddElement<int8_t>(Node::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Node::VT_NAME, name);
  }
  void add_file_path(::flatbuffers::Offset<::flatbuffers::String> file_path) {
    fbb_.AddOffset(Node::VT_FILE_PATH, file_path);
  }
  void add_start_line(int32_t start_line) {
    fbb_.AddElement<int32_t>(Node::VT_START_LINE, start_line, 0);
  }
  explicit NodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Node> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Node>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Node> CreateNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    CodeGraph::NodeType type = CodeGraph::NodeType_Unknown,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> file_path = 0,
    int32_t start_line = 0) {
  NodeBuilder builder_(_fbb);
  builder_.add_start_line(start_line);
  builder_.add_file_path(file_path);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Node> CreateNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    CodeGraph::NodeType type = CodeGraph::NodeType_Unknown,
    const char *name = nullptr,
    const char *file_path = nullptr,
    int32_t start_line = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto file_path__ = file_path ? _fbb.CreateString(file_path) : 0;
  return CodeGraph::CreateNode(
      _fbb,
      id,
      type,
      name__,
      file_path__,
      start_line);
}

struct GraphPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GraphPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_NODES = 6,
    VT_EDGES = 8
  };
  int32_t version() const {
    return GetField<int32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<CodeGraph::Node>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<CodeGraph::Node>> *>(VT_NODES);
  }
  const ::flatbuffers::Vector<const CodeGraph::Edge *> *edges() const {
    return GetPointer<const ::flatbuffers::Vector<const CodeGraph::Edge *> *>(VT_EDGES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           VerifyOffset(verifier, VT_EDGES) &&
           verifier.VerifyVector(edges()) &&
           verifier.EndTable();
  }
};

struct GraphPayloadBuilder {
  typedef GraphPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(int32_t version) {
    fbb_.AddElement<int32_t>(GraphPayload::VT_VERSION, version, 0);
  }
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<CodeGraph::Node>>> nodes) {
    fbb_.AddOffset(GraphPayload::VT_NODES, nodes);
  }
  void add_edges(::flatbuffers::Offset<::flatbuffers::Vector<const CodeGraph::Edge *>> edges) {
    fbb_.AddOffset(GraphPayload::VT_EDGES, edges);
  }
  explicit GraphPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GraphPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GraphPayload>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GraphPayload> CreateGraphPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<CodeGraph::Node>>> nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const CodeGraph::Edge *>> edges = 0) {
  GraphPayloadBuilder builder_(_fbb);
  builder_.add_edges(edges);
  builder_.add_nodes(nodes);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GraphPayload> CreateGraphPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    const std::vector<::flatbuffers::Offset<CodeGraph::Node>> *nodes = nullptr,
    const std::vector<CodeGraph::Edge> *edges = nullptr) {
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<CodeGraph::Node>>(*nodes) : 0;
  auto edges__ = edges ? _fbb.CreateVectorOfStructs<CodeGraph::Edge>(*edges) : 0;
  return CodeGraph::CreateGraphPayload(
      _fbb,
      version,
      nodes__,
      edges__);
}

inline const CodeGraph::GraphPayload *GetGraphPayload(const void *buf) {
  return ::flatbuffers::GetRoot<CodeGraph::GraphPayload>(buf);
}

inline const CodeGraph::GraphPayload *GetSizePrefixedGraphPayload(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<CodeGraph::GraphPayload>(buf);
}

inline bool VerifyGraphPayloadBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<CodeGraph::GraphPayload>(nullptr);
}

inline bool VerifySizePrefixedGraphPayloadBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<CodeGraph::GraphPayload>(nullptr);
}

inline void FinishGraphPayloadBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CodeGraph::GraphPayload> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGraphPayloadBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CodeGraph::GraphPayload> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace CodeGraph

#endif  // FLATBUFFERS_GENERATED_GRAPH_CODEGRAPH_H_
